INSERT INTO region VALUES (1, 'Blekinge län');
INSERT INTO region VALUES (2, 'Dalarnas län');
INSERT INTO region VALUES (3, 'Gotlands län');
INSERT INTO region VALUES (4, 'Gävleborgs län');
INSERT INTO region VALUES (5, 'Hallands län');
INSERT INTO region VALUES (6, 'Jämtlands län');
INSERT INTO region VALUES (7, 'Jönköpings län');
INSERT INTO region VALUES (8, 'Kalmar län');
INSERT INTO region VALUES (9, 'Kronobergs län');
INSERT INTO region VALUES (10, 'Norrbottens län');
INSERT INTO region VALUES (11, 'Skåne län');
INSERT INTO region VALUES (12, 'Stockholms län');
INSERT INTO region VALUES (13, 'Södermanlands län');
INSERT INTO region VALUES (14, 'Uppsala län');
INSERT INTO region VALUES (15, 'Värmlands län');
INSERT INTO region VALUES (16, 'Västerbottens län');
INSERT INTO region VALUES (17, 'Västernorrlands län');
INSERT INTO region VALUES (18, 'Västmanlands län');
INSERT INTO region VALUES (19, 'Västra Götalands län');
INSERT INTO region VALUES (20, 'Örebro län');
INSERT INTO region VALUES (21, 'Östergötlands län');
INSERT INTO hobby VALUES (1, 'GO');
INSERT INTO hobby VALUES (2, 'JOGGING');
INSERT INTO hobby VALUES (3, 'MUSIK');
INSERT INTO hobby VALUES (4, 'ANIME');
INSERT INTO hobby VALUES (5, 'GAMING');
INSERT INTO hobby VALUES (6, 'CRYPTOCURRENCY');
INSERT INTO hobby VALUES (7, 'SHITPOSTING');
INSERT INTO hobby VALUES (8, 'BINGEWATCHING');
INSERT INTO hobby VALUES (9, 'LÄSNING');
INSERT INTO hobby VALUES (10, 'BLOGGING');
INSERT INTO hobby VALUES (11, 'BILAR');
INSERT INTO hobby VALUES (12, 'DANS');
INSERT INTO hobby VALUES (13, 'TRÄNING');
INSERT INTO hobby VALUES (14, 'POESI');
INSERT INTO hobby VALUES (15, 'HANDVERK');
INSERT INTO hobby VALUES (16, 'PYSSEL');
INSERT INTO hobby VALUES (17, 'SLÖJD');
INSERT INTO hobby VALUES (18, 'KUNGFU');
INSERT INTO hobby VALUES (19, 'FOTBOLL');
INSERT INTO hobby VALUES (20, 'HOCKEY');
INSERT INTO hobby VALUES (21, 'INNEBANDY');
INSERT INTO hobby VALUES (22, 'ISHOCKEY');
INSERT INTO hobby VALUES (23, 'SKIDOR');
INSERT INTO hobby VALUES (24, 'SNOWBOARD');
INSERT INTO hobby VALUES (25, 'PUSSEL');
INSERT INTO hobby VALUES (26, 'DATORER');
INSERT INTO hobby VALUES (27, 'FISKNING');
INSERT INTO hobby VALUES (28, 'COSPLAY');
INSERT INTO hobby VALUES (29, 'TABLETOP');
INSERT INTO hobby VALUES (30, 'BRÄDSPEL');
INSERT INTO hobby VALUES (31, 'YOGA');
INSERT INTO hobby VALUES (32, 'FEST');
INSERT INTO hobby VALUES (33, 'BIOGRAF');
INSERT INTO hobby VALUES (34, 'MAT');
INSERT INTO hobby VALUES (35, 'RESTAURANG');

