INSERT INTO region VALUES (1, 'Blekinge län');
INSERT INTO region VALUES (2, 'Dalarnas län');
INSERT INTO region VALUES (3, 'Gotlands län');
INSERT INTO region VALUES (4, 'Gävleborgs län');
INSERT INTO region VALUES (5, 'Hallands län');
INSERT INTO region VALUES (6, 'Jämtlands län');
INSERT INTO region VALUES (7, 'Jönköpings län');
INSERT INTO region VALUES (8, 'Kalmar län');
INSERT INTO region VALUES (9, 'Kronobergs län');
INSERT INTO region VALUES (10, 'Norrbottens län');
INSERT INTO region VALUES (11, 'Skåne län');
INSERT INTO region VALUES (12, 'Stockholms län');
INSERT INTO region VALUES (13, 'Södermanlands län');
INSERT INTO region VALUES (14, 'Uppsala län');
INSERT INTO region VALUES (15, 'Värmlands län');
INSERT INTO region VALUES (16, 'Västerbottens län');
INSERT INTO region VALUES (17, 'Västernorrlands län');
INSERT INTO region VALUES (18, 'Västmanlands län');
INSERT INTO region VALUES (19, 'Västra Götalands län');
INSERT INTO region VALUES (20, 'Örebro län');
INSERT INTO region VALUES (21, 'Östergötlands län');
INSERT INTO hobby VALUES (1, 'GO');